-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 9.625 s <<< FAILURE! - in TestSuite
loginTrue(com.study.cases.LoginTest)  Time elapsed: 4.579 s  <<< FAILURE!
org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8888 refused
	at com.study.cases.LoginTest.getResult(LoginTest.java:80)
	at com.study.cases.LoginTest.loginTrue(LoginTest.java:46)
Caused by: java.net.ConnectException: Connection refused: connect
	at com.study.cases.LoginTest.getResult(LoginTest.java:80)
	at com.study.cases.LoginTest.loginTrue(LoginTest.java:46)

loginFalse(com.study.cases.LoginTest)  Time elapsed: 4.155 s  <<< FAILURE!
org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8888 refused
	at com.study.cases.LoginTest.getResult(LoginTest.java:80)
	at com.study.cases.LoginTest.loginFalse(LoginTest.java:61)
Caused by: java.net.ConnectException: Connection refused: connect
	at com.study.cases.LoginTest.getResult(LoginTest.java:80)
	at com.study.cases.LoginTest.loginFalse(LoginTest.java:61)

